apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapi2
  labels:
    app: expressapi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressapi2
  template:
    metadata:
      labels:
        app: expressapi2
    spec:
      containers:
        - name: expressapi2
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: expressapi-service2
spec:
  selector:
    app: expressapi2
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
