apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapi5
  labels:
    app: expressapi5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressapi5
  template:
    metadata:
      labels:
        app: expressapi5
    spec:
      containers:
        - name: expressapi5
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: expressapi-service5
spec:
  selector:
    app: expressapi5
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
