apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapi7
  labels:
    app: expressapi7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressapi7
  template:
    metadata:
      labels:
        app: expressapi7
    spec:
      containers:
        - name: expressapi7
          env:
            - name: REGISTRY
              value: $REGISTRY
            - name: REPOSITORY
              value: $REPOSITORY
            - name: IMAGE_TAG
              value: $IMAGE_TAG
          image: {{REGISTRY}}/{{REPOSITORY}}:{{IMAGE_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: expressapi-service7
spec:
  selector:
    app: expressapi7
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
