apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapi
  labels:
    app: expressapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressapi
  template:
    metadata:
      labels:
        app: expressapi
    spec:
      containers:
        - name: expressapi
          image: {{REGISTRY}}/{{REPOSITORY}}:{{IMAGE_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: expressapi
spec:
  selector:
    app: expressapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer

