apiVersion: expressapi/v1
kind: Deployment
metadata:
  name: ExpressApi-EKSCluster
  labels:
    app: ExpressApi-EKSCluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ExpressApi-EKSCluster
  template:
    metadata:
      labels:
        app: ExpressApi-EKSCluster
    spec:
      containers:
        - name: ExpressApi-EKSCluster
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ExpressApi-EKSCluster
spec:
  selector:
    app: ExpressApi-EKSCluster
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
