MyRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: 'expressapi'
    RepositoryPolicyText:
      Version: '2023-07-12'
      Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal:
            AWS:
              - 'arn:aws:iam::445522050204:root'
          Action:
            - 'ecr:GetDownloadUrlForLayer'
            - 'ecr:BatchGetImage'
            - 'ecr:BatchCheckLayerAvailability'
            - 'ecr:PutImage'
            - 'ecr:InitiateLayerUpload'
            - 'ecr:UploadLayerPart'
            - 'ecr:CompleteLayerUpload'
