apiVersion: v1
kind: Service
metadata:
  name: expressapi-service
spec:
  selector:
    app: expressapi-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
